#ifndef TCP_SERVER_JSON_DEFINES_HPP__
#define TCP_SERVER_JSON_DEFINES_HPP__

#define MESSAGE_TCP_SERVER_ADDR_KEY					"addr"
#define MESSAGE_TCP_SERVER_PORT_KEY					"port"
#define MESSAGE_TCP_SERVER_DATA_KEY					"data"
#define MESSAGE_TCP_SERVER_DATA_FROM				"from"
#define MESSAGE_TCP_SERVER_DATA_TO					"to"

#define MESSAGE_TCP_SERVER_OPEN_SECURE_KEY			"secure"
#define MESSAGE_TCP_SERVER_OPEN_ADDR_KEY			"addr"
#define MESSAGE_TCP_SERVER_OPEN_PORT_KEY			"port"

#define MESSAGE_SECURE_TYPE_SSL						"ssl"
#define MESSAGE_SECURE_TYPE_PLAIN 					"plain"

#define MESSAGE_TCP_SERVER_CLOSE_ADDR_KEY			"addr"
#define MESSAGE_TCP_SERVER_CLOSE_PORT_KEY			"port"

#define MESSAGE_TCP_SERVER_CLOSE_CLIENT_SERVER_KEY	"server"
#define MESSAGE_TCP_SERVER_CLOSE_CLIENT_CLIENT_KEY	"client"
#define MESSAGE_TCP_SERVER_CLOSE_CLIENT_ADDR_KEY	"addr"
#define MESSAGE_TCP_SERVER_CLOSE_CLIENT_PORT_KEY	"port"

#define MESSAGE_TCP_SERVER_STATUS_SIZE_COUNT_KEY	"count"
#define MESSAGE_TCP_SERVER_STATUS_EPS_LIST_KEY		"list"
#define MESSAGE_TCP_SERVER_STATUS_EP_SECURE_KEY		"secure"
#define MESSAGE_TCP_SERVER_STATUS_EP_ADDR_KEY		"addr"
#define MESSAGE_TCP_SERVER_STATUS_EP_PORT_KEY		"port"
#define MESSAGE_TCP_SERVER_STATUS_EP_CLIENTS_KEY	"clients"

#define MESSAGE_TCP_SERVER_OPTIONS					"options"
#define MESSAGE_TCP_SERVER_OPTIONS_KEEPALIVE		"keepalive"
#define MESSAGE_TCP_SERVER_OPTION_IDLE				"idle"
#define MESSAGE_TCP_SERVER_OPTION_INTERVAL			"interval"
#define MESSAGE_TCP_SERVER_OPTION_COUNT				"count"


#endif /* TCP_SERVER_JSON_DEFINES_HPP__ */
