#ifndef UDP_SERVER_JSON_DEFINES_HPP__
#define UDP_SERVER_JSON_DEFINES_HPP__

#define MESSAGE_UDP_SERVER_ADDR_KEY					"addr"
#define MESSAGE_UDP_SERVER_PORT_KEY					"port"
#define MESSAGE_UDP_SERVER_DATA_KEY					"data"
#define MESSAGE_UDP_SERVER_DATA_FROM				"from"
#define MESSAGE_UDP_SERVER_DATA_TO					"to"

#define MESSAGE_UDP_SERVER_OPEN_ADDR_KEY			"addr"
#define MESSAGE_UDP_SERVER_OPEN_PORT_KEY			"port"

#define MESSAGE_UDP_SERVER_CLOSE_ADDR_KEY			"addr"
#define MESSAGE_UDP_SERVER_CLOSE_PORT_KEY			"port"

#define MESSAGE_UDP_SERVER_STATUS_LIST				"list"
#define MESSAGE_UDP_SERVER_STATUS_EP_ADDR_KEY		"addr"
#define MESSAGE_UDP_SERVER_STATUS_EP_PORT_KEY		"port"

#endif /* UDP_SERVER_JSON_DEFINES_HPP__ */
