#ifndef MAIN_APP_JSON_DEFINES_HPP__
#define MAIN_APP_JSON_DEFINES_HPP__

#define CONTROL_TYPE_STATUS_NUSERS	"nusers"
#define CONTROL_TYPE_STATUS_UID		"uid"

//#define APP_LIST					{MESSAGE_APP_ECHO, MESSAGE_APP_SERIAL, MESSAGE_APP_MONITOR}

#endif /* MAIN_APP_JSON_DEFINES_HPP__ */
