#ifndef UDP_CLIENT_JSON_DEFINES_HPP__
#define UDP_CLIENT_JSON_DEFINES_HPP__

#define MESSAGE_UDP_CLIENT_DATA_LOCAL_ADDR_KEY		"addr"
#define MESSAGE_UDP_CLIENT_DATA_LOCAL_PORT_KEY		"port"
#define MESSAGE_UDP_CLIENT_DATA_KEY					"data"
#define MESSAGE_UDP_CLIENT_LOCAL					"local"

#define MESSAGE_UDP_CLIENT_OPEN_ADDR_KEY			"addr"
#define MESSAGE_UDP_CLIENT_OPEN_PORT_KEY			"port"

#define MESSAGE_UDP_CLIENT_CLOSE_ADDR_KEY			"addr"
#define MESSAGE_UDP_CLIENT_CLOSE_PORT_KEY			"port"

#define MESSAGE_UDP_CLIENT_STATUS_EP_ADDR_KEY		"addr"
#define MESSAGE_UDP_CLIENT_STATUS_EP_PORT_KEY		"port"
#define MESSAGE_UDP_CLIENT_STATUS_EP_LOCAL_KEY		"local"
#define MESSAGE_UDP_CLIENT_STATUS_EP_REMOTE_KEY		"remote"

#endif /* UDP_CLIENT_JSON_DEFINES_HPP__ */
