#ifndef TCP_CLIENT_JSON_DEFINES_HPP__
#define TCP_CLIENT_JSON_DEFINES_HPP__

#define MESSAGE_TCP_CLIENT_DATA_LOCAL_ADDR_KEY		"addr"
#define MESSAGE_TCP_CLIENT_DATA_LOCAL_PORT_KEY		"port"
#define MESSAGE_TCP_CLIENT_DATA_KEY					"data"
#define MESSAGE_TCP_CLIENT_LOCAL					"local"

#define MESSAGE_TCP_CLIENT_OPEN_SECURE_KEY			"secure"
#define MESSAGE_TCP_CLIENT_OPEN_ADDR_KEY			"addr"
#define MESSAGE_TCP_CLIENT_OPEN_PORT_KEY			"port"

#define MESSAGE_SECURE_TYPE_SSL						"ssl"
#define MESSAGE_SECURE_TYPE_PLAIN 					"plain"

#define MESSAGE_TCP_CLIENT_CLOSE_ADDR_KEY			"addr"
#define MESSAGE_TCP_CLIENT_CLOSE_PORT_KEY			"port"

#define MESSAGE_TCP_CLIENT_STATUS_EP_SECURE_KEY		"secure"
#define MESSAGE_TCP_CLIENT_STATUS_EP_ADDR_KEY		"addr"
#define MESSAGE_TCP_CLIENT_STATUS_EP_PORT_KEY		"port"
#define MESSAGE_TCP_CLIENT_STATUS_EP_LOCAL_KEY		"local"
#define MESSAGE_TCP_CLIENT_STATUS_EP_REMOTE_KEY		"remote"

#define MESSAGE_TCP_CLIENT_OPTIONS					"options"
#define MESSAGE_TCP_CLIENT_OPTIONS_KEEPALIVE		"keepalive"
#define MESSAGE_TCP_CLIENT_OPTION_IDLE				"idle"
#define MESSAGE_TCP_CLIENT_OPTION_INTERVAL			"interval"
#define MESSAGE_TCP_CLIENT_OPTION_COUNT				"count"


#endif /* TCP_CLIENT_JSON_DEFINES_HPP__ */
